### PR TITLE
add gridsome to frontend

### PR DESCRIPTION
**Pull request by hussamkhatib**
#### What roadmap does this PR target?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### Please acknowledge the items listed below

- [x] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this PR.

#### Enter the details about the contribution

 added grindsome in static site generator .
the above is discussed  [here](https://github.com/kamranahmedse/roadmap.sh/issues/126)

### CODE REVIEW

**Comment by hussamkhatib** [comment]
okay i will create a PR

**Comment by kamranahmedse** [comment]
I can merge the same. Thanks @hussamkhatib :)

**Comment by Berkmann18** [comment]
It seems like this change hasn't been reflected on https://roadmap.sh/frontend

**Comment by BROGVOIDOVO** [comment]
[]()[]()

**Comment by hussamkhatib** [comment]
@kamranahmedse do I need to do a PR in [roadmap.sh repo](https://github.com/kamranahmedse/developer-roadmap) too

**Comment by BROGVOIDOVO** [comment]
https://github.com/kamranahmedse/developer-roadmap/pull/701/commits/327a01563361dbc82c5ca9bcbb5b9cda3102a155

**Pull request merged**
