### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by bdmorin**
Really like what you did. I added a few things that I think are important for devs to keep an eye on.

### CODE REVIEW

**Comment by OptimusCrime** [comment]
According to the readme you should export the PNG image too.

**Comment by bdmorin** [comment]
Well.. I did, and updated a new imgur link. There was no other images in the repo and I didn't want to add one.

**Comment by lex111** [comment]
@bdmorin [GraphQL is not RESTful](https://www.symfony.fi/entry/what-is-graphql-and-how-does-it-differ-from-rest-apis), is not that why he added to it?

**Comment by OptimusCrime** [comment]
@bdmorin Ups, my mistake. I did not that you changed the URL, I only thought you added https and changed the bmpr file.

**Comment by bdmorin** [comment]
Regarding GraphQL - no, it's not, but I believe it's an important thing to watch/be aware/experiment with when building apis. If you want that taken out, I'd understand.

**Comment by kamranahmedse** [comment]
Hi @bdmorin, thank you for the PR.

I made some changes, and can't merge this because of the conflicts in binary, so I have manually added the changes by looking at your comments above. 

Thank you.

**Pull request closed without merging**
