### PR TITLE
Updated directional@foD8K7V0yIxgeXwl687Bv.md

### PR DESCRIPTION
**Pull request by pyoneerC**
pyoneerC on directional lights.

### CODE REVIEW

**Comment by kenshanta** [comment]
a bit generic, as if AI generated i do declare

**Comment by pyoneerC** [comment]
I write it myself and the gpt guy revised it, fr.

**Comment by dansholds** [comment]
@pyoneerC using GPT to review and reword the content is perfectly ok, thats what it was created to do.

Can you please edit the content to be a single, concise paragraph and add a couple of links, this is the desired format:

```
#Title 

This is a single concise paragraph

Learn more from the following resources:

- [@tag@Title](link)
- [@tag@Title](link)
```

**Review by dansholds — CHANGES_REQUESTED** [review]
As per my comment

**Comment by dansholds** [comment]
Please refer to the contribution guidelines - https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md

**Pull request closed without merging**
