### PR TITLE
render/index.tsx: minor fixes

### PR DESCRIPTION
**Pull request by chiqorein**
Replaced bottom-0 left-0 right-0 top-0 with inset-0 for cleaner positioning Added flexbox centering to properly center the content Added a semi-transparent background with bg-white/90 Created a contained card-like container with padding, rounded corners, and shadow Improved text alignment and spacing

### CODE REVIEW

**Comment by arikchakma** [comment]
Can you please add a before and after image of the changes?

**Comment by arikchakma** [comment]
@chiqorein Can I know why you closed the PR?

**Comment by chiqorein** [comment]
i ain't taking screenshots for every commit message, and explaining how everything works-i thought this repo'd have test cases but reviewing based on screenshots makes no sense, so i didn't want to contribute to it

**Comment by arikchakma** [comment]
Apologies; we currently don’t have test cases. I understand that reviewing without test cases and relying on screenshots can be challenging. We’re actively working to improve the repository, and adding test cases is definitely part of our plan.

Thank you for your feedback.

**Pull request closed without merging**
