### PR TITLE
Add PDF versions. Update contribution guide of README

### PR DESCRIPTION
**Pull request by prosimplecoding**
**1.** I offer PDF versions of roadmaps. Some features of PDF file:
- Printable;
- High quality and others;

_All files are created using Balsamiq._

--------------------------------------------------------------------------
**2.**  Update contribution guide of README:
- Change Balsamiq link to https://balsamiq.cloud/;
- Change "Mockup JSON" to "Wireframe JSON".

### CODE REVIEW

**Comment by jayboyY1** [comment]
+1 407-886-2326

**Comment by BR3NDAN-L8N** [comment]
Thanks for the PDF!

**Comment by hellodit** [comment]
Wow, thanks!

**Comment by kamranahmedse** [comment]
This has been resolved. You may find the printable PDFs through the links below:

- [Frontend Roadmap](https://roadmap.sh/static/roadmaps/pdf/frontend.pdf)
- [Backend Roadmap](https://roadmap.sh/static/roadmaps/pdf/backend.pdf)
- [DevOps Roadmap](https://roadmap.sh/static/roadmaps/pdf/devops.pdf)

**Pull request closed without merging**
