### PR TITLE
Artificial Intelligence - Roadmap

### PR DESCRIPTION
**Pull request by JulianaCP**
#### What roadmap does this PR target?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [X] Artificial Intelligence - Roadmap

#### Please acknowledge the items listed below

- [ ] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing.md) before opening this PR.

#### Enter the details about the contribution

Artificial Intelligence - Roadmap

### CODE REVIEW

**Review by pablo00x — APPROVED** [review]

**Review by ryudesu6445 — APPROVED** [review]

**Review by ryudesu6445 — APPROVED** [review]

**Review by errafaiy — APPROVED** [review]

**Review by Mahmoudibraheeem — APPROVED** [review]

**Comment by afsaneh751** [comment]
> #### What roadmap does this PR target?
> 
> - [ ] Frontend Roadmap
> - [ ] Backend Roadmap
> - [ ] DevOps Roadmap
> - [ ] All Roadmaps
> - [X] Artificial Intelligence - Roadmap
> 
> #### Please acknowledge the items listed below
> 
> - [ ] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
> - [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
> - [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
> - [X] I have read the [contribution docs](../contributing.md) before opening this PR.
> 
> #### Enter the details about the contribution
> 
> Artificial Intelligence - Roadmap

**Comment by afsaneh751** [comment]
Titel

**Comment by afsaneh751** [comment]
Titel

**Comment by afsaneh751** [comment]
سلام  شما ایرانی هستید

**Comment by afsaneh751** [comment]
لطفا جواب بده

**Comment by afsaneh751** [comment]
سلام جواب بده اگه فارسی میتونی تایپ کن لطفا من کار واجب دارم

**Review by 53jk1 — APPROVED** [review]

**Review by afsaneh751 — APPROVED** [review]
Afsaneh09217

**Review by damminhtien — CHANGES_REQUESTED** [review]
I think AI is a large field. I suggest we can separate this roadmap into deeper like ML engineer, big data engineer, etc ...

**Review by Sridhar-rajendran — APPROVED** [review]

**Review by DEEPAKMSI — COMMENTED** [review]
Open
Master

**Comment by McLutzifer** [comment]
This is awesome - you could maybe add **Julia** as a possible Language

**Comment by alaagamar** [comment]
Unsubscribe

**Comment by RodrigoAB93** [comment]
How we can getting start? Create a Telegram's group for discussion. Artificial Inteligence is  a field very large and complex.I think the best way to getting start is create one repository and multiple branch with subject like ML,NLP...

**Review by Mahmoudibraheeem — APPROVED** [review]

**Review by HTML-CODDER — APPROVED** [review]
Lovely and looking great

**Review by Tiz-Max — APPROVED** [review]
Thank you

**Comment by Deandeanice** [comment]
> I think AI is a large field. I suggest we can separate this roadmap into deeper like ML engineer, big data engineer, etc ...

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> Open Master

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> This is awesome - you could maybe add **Julia** as a possible Language

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> Unsubscribe

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> How we can getting start? Create a Telegram's group for discussion. Artificial Inteligence is a field very large and complex.I think the best way to getting start is create one repository and multiple branch with subject like ML,NLP...

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> How we can getting start? Create a Telegram's group for discussion. Artificial Inteligence is a field very large and complex.I think the best way to getting start is create one repository and multiple branch with subject like ML,NLP...

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> Thank you

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by ibandim123** [comment]
This issue finished? Come on people let's do it! AI and Robotic RoadMap, we needed !!

**Comment by sawungrana** [comment]
> This issue finished? Come on people let's do it! AI and Robotic RoadMap, we needed !!

There are still some conflicts, that's why this section doesn't appear on the website. Juts to let you guys know, lots of people would appreciate this branch.

**Comment by ibandim123** [comment]
Some idea, i hope hel
Captura de tela de 2022-02-01 19-39-40
p

**Comment by kpedrok** [comment]
@sawungrana you can find it here [](https://github.com/JulianaCP/developer-roadmap/blob/master/img/ai.png)

**Comment by kpedrok** [comment]
@sawungrana you can find it here [https://github.com/JulianaCP/developer-roadmap/blob/master/img/ai.png](https://github.com/JulianaCP/developer-roadmap/blob/master/img/ai.png)

**Comment by Twest113** [comment]
This is cool

**Comment by kamranahmedse** [comment]
Thanks @JulianaCP -- closing it for now. AI roadmap is in the pipeline and should be launched in the coming weeks.

**Pull request closed without merging**
