### PR TITLE
MongoDB Roadmap

### PR DESCRIPTION
**Pull request by alexbevi**
Roadmap for developers using MongoDB as their developer data platform
image

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Thank you for the PR but we are already working on something for this.

**Comment by alexbevi** [comment]
@kamranahmedse As a Product Manager at MongoDB on the Developer Experience team I'd be more than happy to assist with this initiative. If I can help move this along in any way just let me know.

**Comment by kamranahmedse** [comment]
@alexbevi thank you for offering to help. We have the following textual version of the MongoDB roadmap. If you could help get it reviewed/improved, that would be great:

---

- MongoDB Basics
  - SQL vs NoSQL
  - What is MongoDB?
  - When to use MongoDB?
- MongoDB data model and data types    
  - BSON (Binary JSON) data types
    - Double
    - String
    - Object
    - Array
    - Binary data
    - Undefined
    - ObjectId
    - Boolean
    - Date
    - Null
    - Regular Expression
    - JavaScript
    - Symbol
    - Integer or Int32
    - Timestamp
    - Integer or Int64
    - Decimal128
    - Min key
    - Max key
  - Embedded documents and arrays
- MongoDB collections and documents
  - Creating, reading, updating, and deleting collections and documents
  - Common collection methods and properties
    - countDocuments() and estimatedDocumentCount()
    - find() and findOne()
    - insertOne() and insertMany()
    - updateOne() and updateMany()
    - deleteOne() and deleteMany()
    - createIndex() and dropIndex()
    - validate() and listIndexes()
- MongoDB CRUD (Create, Read, Update, and Delete) operations
  - insert, find, update, and delete operations
  - insertMany, bulkWrite, updateMany and deleteMany operations
  - upsert option
  - write concern
- MongoDB query and projection operators
  - Comparison operators ($eq, $gt, $lt, $gte, $lte, $ne)
  - Logical operators ($and, $or, $not, $nor)
  - Element operators ($exists, $type, $regex)
  - Array operators ($in, $nin, $all, $elemMatch, $size)
  - Projection operators ($project, $include, $exclude, $slice)
- MongoDB indexing and performance optimization
  - Index types (single field, compound, text, and geospatial)
  - Creating and managing indexes
  - Tips for optimizing query performance
- MongoDB data aggregation and pipeline
  - Aggregation framework concepts
    - Concept of pipeline
    - Concept of stages
    - Concept of operators
  - Common pipeline stages ($match, $group, $sort, $project, $skip, $limit, etc.)
  - Using the aggregate() method
- MongoDB transactions
  - Multi-document transactions
  - Retryable writes
- MongoDB installation and setup
  - Installing MongoDB on different operating systems (Windows, Mac, Linux)
    - Downloading the MongoDB Community Server
    - Installing and configuring MongoDB
  - Setting up MongoDB replica sets and sharded clusters
    - Setting up replica sets
    - Setting up sharded clusters
  - MongoDB configuration options and tuning
    - Configuring MongoDB options
    - Tuning MongoDB for performance
  - MongoDB tools and utilities (mongo shell, Compass, etc.)
    - Mongo shell
    - Compass
- MongoDB security (authentication and authorization) 
  - Role-based access control
  - Encryption at rest
  - X.509 certificate authentication
- MongoDB backup and recovery
  - mongodump, mongorestore
  - Cloud-based backups
- MongoDB scaling and performance 
  - Replica sets and sharding
  - Indexing and query optimization
  - Horizontal Scaling
  - Vertical Scaling
  - Read and Write Sharding
  - Auto-Sharding
  - Sharded Cluster Deployment
  - Monitoring and Troubleshooting
  - Capacity Planning
  - Backup and Recovery Strategies for Scaled Systems
  - Scaling for Multiple Data Centers

**Comment by alexbevi** [comment]
@kamranahmedse thanks for sharing the proposed roadmap. I've moved this to a [gist](https://gist.github.com/alexbevi/35af6a32b0c59d2f202125cc02e02a97) so that you can quickly [compare them to see what's been modified](https://gist.github.com/alexbevi/35af6a32b0c59d2f202125cc02e02a97/revisions?diff=split)

**Pull request closed without merging**
