### PR TITLE
Added warning to Vue CLI regarding its maintenance mode

### PR DESCRIPTION
**Pull request by artshade**
Dear Developers,

Thank you very much for the awesome resource and project!

The `create-vue` recommendation was added [2 years](<https://github.com/vuejs/vue-cli/commit/7c0134e653a0f58315ac9b06e940a5c5928b8b0b>) ago by Evan You, and it feels like it must be stated in the feature description here, too.

Best and kind regards :sparkles:

### CODE REVIEW

**Comment by dansholds** [comment]
Hey!

Thanks for creating the PR!

You raise an interesting point but I'm conscious that the link within that content which goes to https://cli.vuejs.org/guide/ does show this warning at the top.

Do you feel like adding a warning here (bare in mind that we don't have deprecation warnings or emojis anywhere else) is really necessary?

**Comment by dansholds** [comment]
It seems like the solution here lays overall updates to the Vue roadmap rather than adding this depreciation warning doesn't it!

I'll close this PR and raise these points internally!

Thanks for raising this, we really appreciate it!

**Comment by skirtles-code** [comment]
@dansholds For what it's worth, we frequently get questions about learning Vue on the Vue Discord server, and occasionally the link to this roadmap gets suggested. But invariably we have to discourage people from using it, because the information is too out of date and would lead beginners in the wrong direction.

If it helps, I made some suggestions a while back about some of the things that might be worth changing: #3741.

**Comment by dansholds** [comment]
> @dansholds For what it's worth, we frequently get questions about learning Vue on the Vue Discord server, and occasionally the link to this roadmap gets suggested. But invariably we have to discourage people from using it, because the information is too out of date and would lead beginners in the wrong direction.
> 
> If it helps, I made some suggestions a while back about some of the things that might be worth changing: #3741.

Ah that's awesome, thanks! 

Feedback like this is invaluable so I'll make sure it's fed back to the team and hopefully we can see some of your suggestions implemented 🤙

I'll keep you updated via the linked suggestion!

**Pull request closed without merging**
