### PR TITLE
Corrected / Improved C++ roadmap

### PR DESCRIPTION
**Pull request by fellalli**
I have corrected and improved some things in the C++ roadmap.

Here are the major changes I have made:
---
[100-installing.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/101-setting-up/100-installing.md) and [101-setting-up/index.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/101-setting-up/index.md)
- MinGW is not a compiler

[101-code-editors.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/101-setting-up/101-code-editors.md)
- Mention Visual Studio here
- Vscode has no built-in support for C++, only extensions

[103-functions/index.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/103-functions/index.md)
- The `printf()` and `scanf()` functions are from the C standard library
- Don't use the void keyword in the parameter in C++

[102-poco.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/libraries/102-poco.md)
- `responseBody` is undefined

Additionally, I have removed every `using namespace std;`, since using that is [not recommended](https://isocpp.org/wiki/faq/coding-standards#using-namespace-std) and therefore a bad habit.

### CODE REVIEW

**Comment by dansholds** [comment]
@fellalli please resolve the conficts, the addition LGTM though 😄

**Comment by fellalli** [comment]
I will do a few more changes in this pr :)

**Comment by dansholds** [comment]
> I will do a few more changes in this pr :)

Ready now?

**Comment by fellalli** [comment]
Yes, ready!👍

**Review by dansholds — APPROVED** [review]
LGTM, lets squash all the commits prior to creating the PR next time though!

**Pull request merged**
