### PR TITLE
Added TypeScript and replaced Postgres with MongoDB in Full Stack Roadmap

### PR DESCRIPTION
**Pull request by Paras-Baweja**
As TypeScript and MongoDB are the most wanted skills as a Full Stack Developer in the Job Market and Postgres is only used in specific projects of Full Stack, it can be learned later easily by the person.

### CODE REVIEW

**Comment by Paras-Baweja** [comment]
Solves #5063

**Review by dev-aly3n — COMMENTED** [review]
For contributions, please visit the [contribution guide](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md). If you want to add a new roadmap or add a new node to an existing roadmap, you must open an issue with the suggestion tag.

**Comment by Paras-Baweja** [comment]
Already made an issue #5063

**Comment by dev-aly3n** [comment]
That's not the point. Maintainers are responsible for adding those suggestions. You should not and cannot add new nodes.
Please follow the [contribution guide](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md).

**Pull request closed without merging**
