### PR TITLE
Further Improvements in Node.js Roadmap.

### PR DESCRIPTION
**Pull request by offensive-vk**
*This PR was a part of merged pr (#6664).*

- Fix Spelling and Grammar Mistakes.
- Fix Wrong URLs.
- Few Deletions.

*A Rare PR Count ⚡ - #6666.*

### CODE REVIEW

**Comment by andreluis-oliveira** [comment]
some notes:

[roadmaps/nodejs/content/using-debugger@XEGTeGWw05xWYOfUo3POE.md]
 - [@official@Official Website]   could be [@official@Debugger - Node.js Documentation] or [@officia@Official Docs]
 -freecodecamp it's not an official link, use @article instead.

[roadmaps/nodejs/content/working-with-databases@5l-lZ8gwVLqqAF_n99vIO.md]
 -- Wikipedia it's not an official link.

**Comment by andreluis-oliveira** [comment]
some notes:

[roadmaps/nodejs/content/[using-debugger@XEGTeGWw05xWYOfUo3POE.md](mailto:using-debugger@XEGTeGWw05xWYOfUo3POE.md)]

[@official@Official Website] could be [@official@Debugger - Node.js Documentation] or [@official@Official Docs]
-freecodecamp it's not an official link, use https://github.com/Article instead.
[roadmaps/nodejs/content/[working-with-databases@5l-lZ8gwVLqqAF_n99vIO.md](mailto:working-with-databases@5l-lZ8gwVLqqAF_n99vIO.md)]
-- Wikipedia it's not an official link.

**Comment by andreluis-oliveira** [comment]
some notes:

[roadmaps/nodejs/content/[using-debugger@XEGTeGWw05xWYOfUo3POE.md](mailto:using-debugger@XEGTeGWw05xWYOfUo3POE.md)]

- [@official@Official Website] could be [@official@Official Docs]
- freecodecamp it's not an official link, use article instead.

[roadmaps/nodejs/content/[working-with-databases@5l-lZ8gwVLqqAF_n99vIO.md](mailto:working-with-databases@5l-lZ8gwVLqqAF_n99vIO.md)]

-- Wikipedia it's not an official link.

**Comment by offensive-vk** [comment]
Sure thing, boss

**Comment by offensive-vk** [comment]
Hey, @kamranahmedse , Can you take a look here?
Thanks.

**Pull request merged**
