### PR TITLE
feat:translate front-end roadmap into Chinese

### PR DESCRIPTION
**Pull request by ScarboroughCoral**
#### What roadmap does this PR target?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### Please acknowledge the items listed below

- [x] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this PR.

#### Enter the details about the contribution

Translate the front-end roadmap into Chinese, and the translated version **need to be checked and reviewed.**

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Thanks @ScarboroughCoral 🙏

**Comment by hszhakka** [comment]
@ScarboroughCoral 逛个街回来发现被你抢先了。继续加油吧。

**Comment by ScarboroughCoral** [comment]
@hszhakka 哈哈，你可以试试后端和devops，前端我也可能一些地方翻译的有些问题，欢迎指正

**Comment by hszhakka** [comment]
> @hszhakka 哈哈，你可以试试后端和devops，前端我也可能一些地方翻译的有些问题，欢迎指正

你翻译到哪一步了？免得重复了。

**Comment by ScarboroughCoral** [comment]
> > @hszhakka 哈哈，你可以试试后端和devops，前端我也可能一些地方翻译的有些问题，欢迎指正
> 
> 你翻译到哪一步了？免得重复了。

我只翻译了前端，后端不太熟悉，暂时不翻译了。

**Comment by hszhakka** [comment]
> > > @hszhakka 哈哈，你可以试试后端和devops，前端我也可能一些地方翻译的有些问题，欢迎指正
> > 
> > 
> > 你翻译到哪一步了？免得重复了。
> 
> 我只翻译了前端，后端和devops不太熟悉，暂时不翻译了。

好，那我接棒吧。

**Comment by ScarboroughCoral** [comment]
@hszhakka 奥利给！

**Pull request merged**
