### PR TITLE
[1839] - Adding official docs and tutorials for Chalk and InquirerJS

### PR DESCRIPTION
**Pull request by Platiplus**
## Issue
[1839-Add Content to NodeJS roadmap](https://github.com/kamranahmedse/developer-roadmap/issues/1839)

I added information for Chalk and Inquirer. I used them personally together a couple of weeks ago and they're awesome!

Please label this PR as 'hacktoberfest-accepted', If it is able to merge.

### CODE REVIEW

**Comment by Platiplus** [comment]
@kamranahmedse Can you please take a look at this? A pull request made yesterday after mine was already made have been merged and I had to resolve conflicts.

**Comment by Platiplus** [comment]
@kamranahmedse, not cool man, a lot of PRs from the same guy were created and approved after mine was it, and no attention to this even after tagging... Why open hacktoberfest contributions if you're not caring about other people?

**Comment by kamranahmedse** [comment]
@Platiplus the conflicts are expected and I am not expecting you to resolve the conflicts. I resolve the conflicts before merging. There have been 300+ pull requests and I haven't closed any which had the quality content. Reviewing PRs take time so be patient -- no need to call out in such a manner!

**Comment by Platiplus** [comment]
@kamranahmedse Sorry, I do not mean to be disrespectful, I just got frustrated to see pull requests to files I already opened being created after mine and actually being merged. I actually did not know conflicts were expected, sorry for the disturbance, you don't need to rush reviews.

**Pull request merged**
