### PR TITLE
Adding SoloLearn as a source in java-fundamentals

### PR DESCRIPTION
**Pull request by KratikJain10**
Hello!
Myself Kratik Jain.
In Java Developer Roadmap ,I added solo learn as a learning source in Java Fundamentals , Its a free source with a great learning environment,
Kindly Consider My contribution and assign me badge for hactoberfest.
Thank You

### CODE REVIEW

**Comment by KratikJain10** [comment]
@kamranahmedse Kindly review and consider it ,if its ok .#Hactoberfest2022

**Comment by kamranahmedse** [comment]
Thank you for your contribution but the content you have added is behind the registration and we are only adding content which doesn't require any registration.

**Comment by KratikJain10** [comment]
@kamranahmedse .oh ok,no problem.
Thank you.

**Comment by KratikJain10** [comment]
@kamranahmedse so can i add sources which do not require any registration?

**Pull request closed without merging**
