### PR TITLE
Bengali Translations initiated

### PR DESCRIPTION
**Pull request by zonayedpca**
I want to translate it into my own language so that our people can understand it more easily. Please let me know if it is allowed or not. Thanks :)

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Hey, thanks for the PR. I would rather suggest you to do it in the fork and then share the link with me, I will put it in the repository :)

**Comment by zonayedpca** [comment]
Thanks bro... Can I use these images in my blog post?

**Comment by raunakhajela** [comment]
What images?

**Comment by kamranahmedse** [comment]
Yes, as long as you refer back to the repository.

**Pull request closed without merging**
