### PR TITLE
there's a grammatical error!

### PR DESCRIPTION
**Pull request by vishal5251**
#### What roadmap does this PR target?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### Please acknowledge the items listed below

- [ ] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this PR.

### CODE REVIEW

**Comment by carlosdeque-s** [comment]
I understand that these roadmaps are - highly opinionated. The purpose is

 **to not to include**

 everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.

**Comment by kamranahmedse** [comment]
Thanks

**Comment by vishal5251** [comment]
i'd have seen those flaws y u not merged this pull request

**Comment by afsaneh751** [comment]
سلام خوبی

**Comment by parsakhosravani** [comment]
سلام جانمSent from my Samsung Galaxy smartphone.
-------- Original message --------From: afsaneh751 <notifications@github.com> Date: 10/21/20  5:48 AM  (GMT+03:30) To: kamranahmedse/developer-roadmap <developer-roadmap@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [kamranahmedse/developer-roadmap] there's a grammatical error! (#785) 

سلام خوبی

**Pull request merged**
