### PR TITLE
🚀 Add data engineering roadmap

### PR DESCRIPTION
**Pull request by mostafaghadimi**
In this pull request, We, as DataBurst team, are excited to introduce a comprehensive new roadmap for data engineers (Individual Contributors). This roadmap is designed to provide a clear and structured path for data engineering processes, outlining key milestones, technologies, and skills essential for individuals. It encompasses various aspects of data engineering, including data ingestion, storage, processing, and orchestration, offering a holistic view of the data engineering lifecycle.

[Link to the roadmap](https://roadmap.sh/r?id=660005ca6deb533d6e21bca9)

### CODE REVIEW

**Comment by niyushabaghayi** [comment]
@kamranahmedse Would you please review this? and if it's fine merge it to the repository?

**Review by NormTurtle — COMMENTED** [review]
its good

**Comment by mostafaghadimi** [comment]
@NormTurtle Thanks for your review. What are the remained steps to merge it?

**Comment by kamranahmedse** [comment]
Thank you for the PR @mostafaghadimi -- looks really nice!

In future, you should submit the roadmap link in an issue instead of a PR. We have a different process for launching official roadmaps (there are different tools we use). As a next step, we will get it reviewed and if everything looks good we should publish it in the next few weeks.

**Comment by niyushabaghayi** [comment]
@kamranahmedse Would you please let us know when will you merge this PR?

**Pull request closed without merging**
