### PR TITLE
Add blockchain roadmap

### PR DESCRIPTION
**Pull request by danielgruesso**
#### What roadmap does this PR target?

- [ ] Code Change
- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps
- [ ] Guides

#### Please acknowledge the items listed below

- [x] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this PR.

#### Enter the details about the contribution

Adds blockchain roadmap to the list of available roadmaps

### CODE REVIEW

**Comment by BOLT04** [comment]
Hi @danielgruesso this is a pretty cool roadmap 💯. Could you share how you created the .json file for this new roadmap: `public/project/blockchain.json`?
 Is there any tool or script that does this?

If you could share how you did it I'd appreciate it a lot 🙂 .
Thanks!

**Comment by kamranahmedse** [comment]
Thanks for the contribution @danielgruesso — I will have a look at it this week.

@BOLT04 it's made using Balsamiq.

**Comment by BOLT04** [comment]
> Thanks for the contribution @danielgruesso — I will have a look at it this week.
> 
> @BOLT04 it's made using Balsamiq.

thanks for the answer @kamranahmedse 👍. Is there a way to start designing a roadmap in balsamiq? Maybe import from a JSON file of another roadmap?
What do you recommend to start?

**Comment by danielgruesso** [comment]
Hello @kamranahmedse, following up on this PR. Thanks.

**Comment by danielgruesso** [comment]
Hey @kamranahmedse, wanted to follow up on this. Thanks.

**Comment by kamranahmedse** [comment]
Thank you @danielgruesso — changes have been merged in https://github.com/kamranahmedse/developer-roadmap/pull/1517 and [the roadmap is live](https://roadmap.sh/blockchain) 🙏

**Comment by ank5-d** [comment]
Thanks bro for block chain guidance

**Pull request closed without merging**
