### PR TITLE
add TVM-Based blockchains

### PR DESCRIPTION
**Pull request by ilyar**
resolved conflict for #3671

roadmap
#3669

### CODE REVIEW

**Comment by kamranahmedse** [comment]
This will not have any impact on the roadmap. Roadmap JSON file needs to be modified as well. Could you please open an issue with this PR. We are currently [redrawing all the roadmaps using our own editor](https://github.com/kamranahmedse/developer-roadmap/pull/5897) and will take it up during that. Thank you!

**Comment by ilyar** [comment]
@kamranahmedse Unfortunately, it is unclear how to edit the roadmap data in the editor. It makes sense to assume there should be import and export for JSON data, but I couldn't find them. I also couldn't find any explanations in the project documentation. Could you please advise on how to edit it?

**Comment by ilyar** [comment]
@kamranahmedse Unfortunately, it is unclear how to edit the roadmap data in the editor. It makes sense to assume there should be import and export for JSON data, but I couldn't find them. I also couldn't find any explanations in the project documentation. Could you please advise on how to edit it?

```bash
pnpm editor-roadmap-content blockchain

> roadmap.sh@1.0.0 editor-roadmap-content /home/ilyar/code/developer-roadmap
> tsx scripts/editor-roadmap-content.ts "blockchain"

Only Editor Rendered Roadmaps are allowed
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by kamranahmedse** [comment]
Thanks @ilyar -- this has been implemented in the revised blockchain roadmap
https://roadmap.sh/blockchain

**Pull request closed without merging**
