### PR TITLE
New relic

### PR DESCRIPTION
**Pull request by DabHands**
I added New Relic to the list of monitoring tools. Is there a better way to monitor your infrastructure?

### CODE REVIEW

**Comment by diego-vieira** [comment]
@DabHands what about sentry?

**Comment by DabHands** [comment]
@diego-vieira I have never used Sentry but a quick glance at their features reveals that it will be a great tool. The truth is there are a lot of tools out there. Some will make the list some won't.

**Comment by ascendbruce** [comment]
@diego-vieira @DabHands I guess New Relic, Skylight, Scout are similar tools (performance monitoring). And Sentry, Bugsnag, AirBrake are similar (exception notifier).

**Comment by diego-vieira** [comment]
@ascendbruce indeed, that makes more sense.

**Comment by DabHands** [comment]
@ascendbruce you are right. But the heading is 'Monitoring and Alerting' not 'Performance monitoring and Exception notifier'. So I believe the heading 'Monitoring and Alerting' captures everything. Where @diego-vieira and I could have gotten it wrong is to think New Relic and Sentry perform the same function.

**Pull request closed without merging**
