### PR TITLE
Updated create-react-app to create-next-app in React roadmap

### PR DESCRIPTION
**Pull request by AmineAouragh**
According to the issue #4580 the React roadmap still has create-react-app as a React CLI tool to create new React projects. But as of now the React team no longer recommends using create-react-app but instead recommends picking one of the React-powered frameworks popular in the community like Next.js so i updated the React CLI to create-next-app.

### CODE REVIEW

**Comment by AbdelrhmanX7** [comment]
Hey @AmineAouragh, this should be a simple task that only requires a single file change, but I noticed that around 17 files have been modified, and most of them are unrelated to the issue.

**Comment by AmineAouragh** [comment]
Hey Abderahman yeah absolutely you are right. I don't understand why commits from other pull requests are being added in this pull request. There is a problem.

**Comment by AbdelrhmanX7** [comment]
1- you need to sync your master fork with the developer-roadmap master branch
2- when you create a new branch do thist
    - git checkout -b your-branch-name origin/master (don't forget to stash save any uncommit files)
    - git pull origin master (to update your branch with master base)

**Comment by arikchakma** [comment]
@AmineAouragh Can you please resolve the conflicting files? It could have been just one file.

**Comment by alinkedd** [comment]
@AmineAouragh
Next.js is already located in `Frameworks` group.
I suggest we should either remove CRA completely or replace it with Parcel as it's mentioned in docs.

**Pull request closed without merging**
