### PR TITLE
fix(typo): fixed typo in cpp namespaces

### LINKED ISSUE #4121: [Typo] Error in "namespace" Section - Incorrect Usage of "using" Keyword
### Description:
I have identified a typo error in the "namespace" section of the code/documentation. Specifically, there is an incorrect usage of the "using" keyword. I would like to rectify this issue by proposing a fix to ensure the correct usage of the "using" keyword within the namespace section.

### PR DESCRIPTION
**Pull request by balaji-sivasakthi**
fix #4121

### CODE REVIEW

**Comment by ThDag** [comment]
good issue fix 👍

**Comment by balaji-sivasakthi** [comment]
@kamranahmedse ?

**Comment by ThDag** [comment]
? 👍

**Comment by balaji-sivasakthi** [comment]
@ThDag want to say something?

**Comment by ThDag** [comment]
> @ThDag want to say something? 

yes 👍

**Review by arikchakma — APPROVED** [review]
Thank You ❤️

**Pull request merged**
