### PR TITLE
Fixed typo, was konwledge now knowledge.

### PR DESCRIPTION
**Pull request by kieran-obrien**
## "Pick a Language" section has typo in the following paragraph: Learn the language and build some CLI apps to practice your konwledge. 

<em>This is my first pull request so forgive me if I've not done this correctly, apologies!</em>

### CODE REVIEW

**Comment by fellalli** [comment]
Congratulations on submitting your first PR \:)

**Comment by arikchakma** [comment]
Thank you for the PR, but please avoid directly modifying roadmap JSON files.

@dansholds could you please take note of this?

**Comment by dansholds** [comment]
> Thank you for the PR, but please avoid directly modifying roadmap JSON files.
> 
> @dansholds could you please take note of this?

I have said this countless times in PRs and then closed them.

**Comment by kieran-obrien** [comment]
> 

Will take note of this, sorry for any hassles! Appreciate the feedback!

**Pull request closed without merging**
