### PR TITLE
Documentation for bash scripting

### PR DESCRIPTION
**Pull request by neerajmanivarnan**
Documentation for bash scripting added for the  road-map of DevOps.
Only a link to the tutorial for bash scripting was provided.

### CODE REVIEW

**Comment by neerajmanivarnan** [comment]
Pull Request Summary:
I've made updates to the website content in the `src/data/roadmaps/devops/content/102-live-in-terminal/scripting` path  to the100-bash-scripting.md . The changes aim to provide more clarity.
Thank you for reviewing

**Comment by neerajmanivarnan** [comment]
@arikchakma please review this

**Comment by arikchakma** [comment]
@neerajmanivarnan Thanks for the PR, I'll check it out soon.

**Comment by arikchakma** [comment]
Thank you for the PR but please try to avoid copy-pasting from ChatGPT in the future.

**Pull request closed without merging**
