### PR TITLE
added a new graphQL

### PR DESCRIPTION
**Pull request by PranjalSK03**

### CODE REVIEW

**Comment by PranjalSK03** [comment]
added new content in backend roadmap

**Comment by PranjalSK03** [comment]
@kamranahmedse please tell me if this goes fine with you

**Comment by kamranahmedse** [comment]
This won't add the topic to the roadmap. Please have a look at the contribution guidelines for suggesting/adding topics to existing nodes.

**Comment by PranjalSK03** [comment]
ok got it, thanks for your response.

**Pull request closed without merging**
