### PR TITLE
Java roadmap - Added newer Files.* API for reading Files

### PR DESCRIPTION
**Pull request by leni-kirilov**
added newer Files.* API with articles

### CODE REVIEW

**Comment by dansholds** [comment]
@leni-kirilov Please put this PR in draft and finish what you're doing with the Java roadmap, then set me as a reviewer when you're done, thanks!

**Comment by leni-kirilov** [comment]
@dansholds you want me to combine all my changes in a single PR ? I thought smaller ones were easier to review but ok.
I've created a new one in the meantime. Ignore it and I'll combine it here

**Comment by leni-kirilov** [comment]
to merge https://github.com/kamranahmedse/developer-roadmap/pull/5945 in this one

**Comment by dansholds** [comment]
> @dansholds you want me to combine all my changes in a single PR ? I thought smaller ones were easier to review but ok. I've created a new one in the meantime. Ignore it and I'll combine it here

Due to volume of content and copy PRs we get, large PRs for content changes are not difficult to review as they're typically just a couple of lines changes per line 👍

I'll check and merge all your PR's now 👍

**Review by dansholds — APPROVED** [review]

**Pull request merged**
