### PR TITLE
Fixed Position of the Navigation Bar #7302

### PR DESCRIPTION
**Pull request by Epik-Whale463**
Fixed Position of the Navigation Bar 
As a user scroll down the page the navigation bar does not scroll alongs and if someone wants to access the feature of the navigation bar from the end of the page he/she is able to access it

### CODE REVIEW

**Comment by Epik-Whale463** [comment]
Please review it and merge!

**Comment by Epik-Whale463** [comment]
[Uploading Screencast from 2024-10-02 23-00-11.webm…]()

**Review by offensive-vk — COMMENTED** [review]
cc @arikchakma

**Comment by arikchakma** [comment]
@Epik-Whale463 Could you please attach an image or video of what you have updated?

**Comment by Epik-Whale463** [comment]
[Screencast from 2024-10-02 23-00-11.webm](https://github.com/user-attachments/assets/09808777-26bd-448a-9fa8-3f246cf3610d)

**Comment by Epik-Whale463** [comment]
@arikchakma please review it , also Can you add the hacktoberfest tag to this issue?

**Comment by arikchakma** [comment]
> @arikchakma please review it , also Can you add the hacktoberfest tag to this issue?

I am unsure about this feature though, @kamranahmedse what do you think?

**Comment by kamranahmedse** [comment]
Thank you for the PR, but please do not work on such changes without asking first in an issue. We will be redesigning the navigation soon so it doesn't make sense to change this now.

**Pull request closed without merging**
