### PR TITLE
Readme file in a organised way

### PR DESCRIPTION
**Pull request by Kishore007raj**
I organized the README file in a very structured way by grouping related topics and sorting each group alphabetically. This way, programming enthusiasts can benefit from both methods and choose their favorite language to start programming.

### CODE REVIEW

**Review by dansholds — CHANGES_REQUESTED** [review]
@Kishore007raj  This is a thoughtful contribution that I'm sure will help people find what they need faster when coming to the repo but just a couple of changes please:

1. You have committed your package-lock.json file, let's remove that!
2. If we're going to sort by type lets sort the topics alphabetically and then sort the roadmaps within those topics alphabetically.

**Comment by Kishore007raj** [comment]
ok will do it !!

**Comment by Kishore007raj** [comment]
I did all the changes requested by you!!

**Comment by dansholds** [comment]
@Kishore007raj Why is there a section for language specific but Go, Rust and others are in a different section?

**Comment by dansholds** [comment]
Hey @Kishore007raj I appreciate the effort that you've put behind this PR, having spoken internally we are not going to go ahead with reorganizing the README in the suggested way.

It's currently deliberately organized by roadmap popularity, although we do agree it needs a refresh! So we will work on that internally.

Hopefully you can be happy with the fact that you have raised to us that the README is getting a little outdated!

**Pull request closed without merging**
