### PR TITLE
Fix: Comment out `howtoflutter.dev` (site down) and update tag from `…

### PR DESCRIPTION
**Pull request by SOUMITRO-SAHA**
Fix:
Commented out the howtoflutter.dev link (site down) and updated the tag from @article@Variables to @official@Variables #6888.

### CODE REVIEW

**Comment by kenshanta** [comment]
Better remove the commented code.

Not sure if leaving comments in the code is allowed or not so I'll open a question/suggestion regarding this topic

**Comment by SOUMITRO-SAHA** [comment]
I left the comment because, in the future, when the site goes live or if they want to add something else in that area, it could be helpful. I can remove it if any contributor or maintainer requests it. Since there hasn’t been any discussion on this matter, I decided to leave it for now, but I’m happy to make any changes if needed.

Thank you, @kenshanta , for bringing up this matter for further discussion.

**Comment by kenshanta** [comment]
I've opened a question issue #6934 regarding this topic.

**Comment by dansholds** [comment]
An outright deletion is the method we want to use 🤙

**Pull request merged**
