### PR TITLE
Added roadmap for solution design

### PR DESCRIPTION
**Pull request by thomas-jakemeyn**
Hello @kamranahmedse,

You did a very good job at designing those 3 roadmaps.

With this PR, I have tried to draw a comparable roadmap for _Solution Design_, which is, in my opinion, an essential learning track for a software engineer. I hope you will like it!

# Introduction
intro

# Solution Design Roadmap
solution-design

### CODE REVIEW

**Comment by thomas-jakemeyn** [comment]
@kamranahmedse, any comment on this proposition would be appreciated ;)

**Comment by thomas-jakemeyn** [comment]
Hello @kamranahmedse, I am eager to get your feedback on this PR.

**Comment by murashandme** [comment]
@kamranahmedse, please react, Thomas made great job ☺

**Comment by thomas-jakemeyn** [comment]
@kamranahmedse, any feedback on this PR?

**Comment by olusoladavid** [comment]
@thomas-jakemeyn Awesome stuff. I really like this. It may not fit the "2018 Developer Roadmap" outrightly because it deals with a more general and opinionated topic. However, if this doesn't get merged, you should consider creating a separate repository for it and maybe request a backlink from this roadmap repo in the context of "additional resources".

**Comment by kamranahmedse** [comment]
Hey @thomas-jakemeyn, sorry for the late reply, I have been extremely busy lately and did not get the chance to look into it. I gave it a quick look just now and it looks good. Will probably pull it in by the end of this week. Again, thanks for the effort that you put into it.

**Comment by kamranahmedse** [comment]
Thanks for the PR. I looked at it and although it looks good, IMO it would be suitable as an article rather than including it as a roadmap. However, I am planning to add the links to similar roadmaps created by people and would link it in the readme.

**Pull request closed without merging**
