### PR TITLE
Added Definition of an AI Engineer

### PR DESCRIPTION
**Pull request by 2div**
Hey @offensive-vk 
I added Definition of an AI Engineer.
Please check it
Thank you

### CODE REVIEW

**Review by offensive-vk — COMMENTED** [review]
Good job!

**Comment by 2div** [comment]
> Good job!

Thank you

**Comment by 2div** [comment]
> Good job!

Hi @offensive-vk 

can you please accept the PR.

Thank you

**Comment by 2div** [comment]
HI @kamranahmedse 

can accept and merg my PR.

**Comment by offensive-vk** [comment]
Unfortunately, Your PR doesn't follow our contributing guidelines. Navigate to https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md for further clarification.

Also look out for conflicting PRs with the same content.

Thanks

**Comment by dansholds** [comment]
Please refer to the contribution guidelines - https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md

**Comment by 2div** [comment]
> Unfortunately, Your PR doesn't follow our contributing guidelines. Navigate to https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md for further clarification.
> 
> Also look out for conflicting PRs with the same content.
> 
> Thanks

Hi @dansholds  I think when I submitted my PR, there weren't any others. However, since my PR wasn't accepted, someone else created one that got approved, leading to this conflict. I'll go ahead and delete my PR.

**Pull request closed without merging**
