### PR TITLE
Refractor QA Roadmap - 1st

### PR DESCRIPTION
**Pull request by offensive-vk**
> [!TIP]
> ## QA Roadmap - Part 1

**Topic Links Fixes and Improvements.**

### CODE REVIEW

**Review by arikchakma — APPROVED** [review]

**Comment by offensive-vk** [comment]
hey @arikchakma , do you use discord?

**Comment by offensive-vk** [comment]
are you an expert innit?

**Comment by arikchakma** [comment]
I would say decent, why?

**Comment by arikchakma** [comment]
Ahh okay, let me know if you want to know anything about it. Although I am not that active in Discord, you can still ping me there too.

**Comment by offensive-vk** [comment]
@arikchakma , Thanks buddy, i will be in touch.
Can you Review my other PRs too.
Thanks.

**Comment by arikchakma** [comment]
Sure, give me some time. I will review them ASAP😊

**Pull request merged**
