### PR TITLE
Updated Prompt Hacking

### PR DESCRIPTION
**Pull request by SatyamVyas04**
Added content support for Jailbreaking, including articles, research papers and resources on the same.

### CODE REVIEW

**Comment by SatyamVyas04** [comment]
@dansholds 🙌

**Review by dansholds — CHANGES_REQUESTED** [review]
Please read the contribution guide and adjust your PR accordingly

**Comment by SatyamVyas04** [comment]
Ohh, minimum of two contributions, missed that. Will add other prompt hacking topics as well, and make a commit for the same 👍🏻

**Comment by dansholds** [comment]
> Ohh, minimum of two contributions, missed that. Will add other prompt hacking topics as well, and make a commit for the same 👍🏻

I wasn't talking about hacktoberfest contributions I was talking about contributions in general, have a read of the guidelines and look at the typing of the topics 🤙🏻

**Pull request closed without merging**
