### PR TITLE
Gitlab Error in png #705 resolved

### PR DESCRIPTION
**Pull request by Upinder123**
#### What roadmap does this PR target?

- [ ] Frontend Roadmap
- [x ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### Please acknowledge the items listed below

- [ ] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this PR.

### CODE REVIEW

**Review by johnlegend3476 — APPROVED** [review]

**Review by johnlegend3476 — APPROVED** [review]
Johnlegend3476@gmail.com

**Comment by ole-h** [comment]
Конфликтующие файлы
img/devops.png

**Review by 53jk1 — APPROVED** [review]

**Review by damminhtien — APPROVED** [review]

**Comment by kamranahmedse** [comment]
Thanks Upinder, this has been fixed.

**Comment by artigasmarcelo** [comment]
POR FAVOR ME TIRAR DA LISTA DE TRANSMISSÃO!
OBRIGADO!    Em sexta-feira, 3 de dezembro de 2021 10:29:25 BRT, Kamran Ahmed ***@***.***> escreveu:  
 
 


Thanks Upinder, this has been fixed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ashvith** [comment]
> Thanks Upinder, this has been fixed.

Unfortunately, no. The typo is still there.

**Pull request closed without merging**
