### PR TITLE
Feature: Pull Requests Labelling System.

### PR DESCRIPTION
**Pull request by offensive-vk**
>[!TIP]
> ## Labels Pull Request Based on the File Changes.

- `.github/labeler.yml` - To match the directory or file pattern that is modified.
- `.github/label-pr.yml` - To automatically label pull requests using `GITHUB_TOKEN`.
- `.github/labeler.yml` - Some labels are new, that doesn't exists in Roadmap Repository.

## Live Action:
- https://github.com/offensive-vk/developer-roadmap/pull/10
- https://github.com/offensive-vk/developer-roadmap/pull/8

**Ignore the Failing workflow for this pull request.**

### CODE REVIEW

**Comment by offensive-vk** [comment]
**Relating to CI/CD**

Hey, @kamranahmedse , Please review and the merge these changes as soon as possible. The workflows are failing because of this, so many red crosses in Actions tab lol. 

Thank you.

**Comment by dansholds** [comment]
> **Relating to CI/CD**
> 
> Hey, @kamranahmedse , Please review and the merge these changes as soon as possible. The workflows are failing because of this, so many red crosses in Actions tab lol.
> 
> Thank you.

They're all failures because of you, on your branch though 😂

**Comment by kenshanta** [comment]
@offensive-vk get it together m8

**Comment by offensive-vk** [comment]
@kenshanta bro, what do you think about UK or London? idk

**Comment by dansholds** [comment]
@offensive-vk @kenshanta lets try to keep it on topic!

**Comment by offensive-vk** [comment]
### aight m8 , please dont ban me, wont happen again

https://github.com/user-attachments/assets/e367d30b-7bdc-4715-9b7c-7b30ba9b376b

**Comment by offensive-vk** [comment]
Any updates over here? This can wait, probably ✌️

**Comment by kenshanta** [comment]
@offensive-vk it won't be reviewed until the deployment checks are resolved.
[reference](https://github.com/kamranahmedse/developer-roadmap/actions/runs/10713585094/job/29705848627?pr=7003)

**Comment by offensive-vk** [comment]
😂 @kenshanta m8, It's not about the failing workflow, the maintainers (Kamran) are busy elsewhere, they just need some more time i guess, eh?

Workflow will pass after this pr has merged, do you trust me or not m8?

I have written thousands of Actions workflows, pipelines, dockerfiles. So Dont you worry. ⚡
*Keep contributing to Roadmap.sh*

**Comment by offensive-vk** [comment]
@dansholds , who's the incharge of CI/CD in here mate

**Comment by kamranahmedse** [comment]
@offensive-vk we appreciate your contributions, but please avoid tagging people unnecessarily and using condescending tone in your comments. Keep it respectful and on-topic. This isn't the place for off-topic remarks or pushing others. Continued behavior like this will lead to a ban. Feel free to step back if you can't comply.

**Comment by offensive-vk** [comment]
Hey Kamran, I’m really sorry if I came across the wrong way! I was just trying to be funny and wasn’t meaning to disrespect anyone. I’ll be more mindful going forward.

Thanks.

**Pull request closed without merging**
