### PR TITLE
fixed broken link issue

### LINKED ISSUE #5019: Link Broken!
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

In the backend roadmap, a topic called **HATEOAS** redirects me to a video in youtube that is private right now.

screenshoot

As a suggest i would remove the link and put [this](https://www.geeksforgeeks.org/hateoas-and-why-its-needed-in-restful-api/) helpfull article

### Output from browser console (if any)

_No response_

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by neerajmanivarnan**
This PR fixes #5019 
New link has been added .

Changes have been made to the file "104.hateoas.md" in the path
/src/data/roadmaps/backend/content/109-apis

### CODE REVIEW

**Comment by neerajmanivarnan** [comment]
@arikchakma can you please review my PR?

**Comment by dev-aly3n** [comment]
@LopesLs , who opened that issue, mentioned, "I am willing to submit a pull request for this issue."

You shouldn't submit a pull request for such an issue. Please close this and let @LopesLs fix it.

**Comment by neerajmanivarnan** [comment]
> @LopesLs , who opened that issue, mentioned, "I am willing to submit a pull request for this issue."
> 
> You shouldn't submit a pull request for such an issue. Please close this and let @LopesLs fix it.

Seems like the issue has been open for 4 days.That's why I picked the issue and worked on it

**Comment by LopesLs** [comment]
> Seems like the issue has been open for 4 days.That's why I picked the issue and worked on it

It was a misunderstanding, i was waiting for some kind of answer to start collaborating, but now I can solve this problem very quickly.

**Comment by neerajmanivarnan** [comment]
> > Seems like the issue has been open for 4 days.That's why I picked the issue and worked on it
> 
> It was a misunderstanding, i was waiting for some kind of answer to start collaborating, but now I can solve this problem very quickly.

Okay.Apologies for the misunderstanding.I will close the PR now

**Pull request closed without merging**
