### PR TITLE
Add content links to 'Git / Version Control' section

### PR DESCRIPTION
**Pull request by Kaperskyguru**

### CODE REVIEW

**Comment by dansholds** [comment]
@Kaperskyguru Before you start submitting any more PR's please note the following:

1. If you're going to create valuable contributions to the project please take the time to collate **all** the suggested changes into **one** pull request.
2. We don't accept self-promotion PR's, which your current four PR's are, apologies. 

(I'm going to close your other PR's with no comment so refer to this one.)

**Comment by Kaperskyguru** [comment]
Hey @dansholds 

First, I needed to learn how to add the PR. I clicked on the website, and it took me to the individual pages.

Lastly, the links are not about self-promotion but to my favorite technical writing blog. The content is well-written and matches the specific purpose.

I'm working on adding other links, but I must ensure they match the purpose and are well-written. 

If you will consider, I have added one PR with all the changes.

**Comment by dansholds** [comment]
> Hey @dansholds 
> 
> First, I needed to learn how to add the PR. I clicked on the website, and it took me to the individual pages.
> 
> Lastly, the links are not about self-promotion but to my favorite technical writing blog. The content is well-written and matches the specific purpose.
> 
> I'm working on adding other links, but I must ensure they match the purpose and are well-written. 
> 
> If you will consider, I have added one PR with all the changes.
> 

The articles you linked are written by you and on platforms founded by you, no?

I'm happy to be corrected if I'm mistaken 😀

If this is the case then let's keep it to one link in one location rather than multiple.

**Comment by Kaperskyguru** [comment]
> > Hey @dansholds
> > First, I needed to learn how to add the PR. I clicked on the website, and it took me to the individual pages.
> > Lastly, the links are not about self-promotion but to my favorite technical writing blog. The content is well-written and matches the specific purpose.
> > I'm working on adding other links, but I must ensure they match the purpose and are well-written.
> > If you will consider, I have added one PR with all the changes.
> 
> The articles you linked are written by you and on platforms founded by you, no?
> 
> I'm happy to be corrected if I'm mistaken 😀
> 
> If this is the case then let's keep it to one link in one location rather than multiple.

Thanks.

I will update the PRs and send again.

**Comment by dansholds** [comment]
@Kaperskyguru Sorry I meant if this _isn't_ the case.

**Pull request closed without merging**
