### PR TITLE
feat: implement activity stream

### PR DESCRIPTION
**Pull request by arikchakma**
image

### CODE REVIEW

**Comment by kamranahmedse** [comment]
@arikchakma let's convert user progresses to this component (and use similar grid) and move the activity under the progresses to make it use less space.

image

**Comment by arikchakma** [comment]
> @arikchakma let's convert user progresses to this component (and use similar grid) and move the activity under the progresses to make it use less space.
> 
> image

What about the `clear progress` or `share progress` actions?

**Comment by kamranahmedse** [comment]
It could be a little vertical ellipsis button to show the menu dropdown on the far right side of the progress.

image

**Comment by arikchakma** [comment]
> It could be a little vertical ellipsis button to show the menu dropdown on the far right side of the progress.
> 
> image

image

What do you think?

**Pull request merged**
