### PR TITLE
Added Contents to OOPs, Packages, JVM, Threads in Java Roadmap #1529

### PR DESCRIPTION
**Pull request by dmdbilal**
issue #1529

I've added contents to OOPs, Packages, JVM, Threads in Java Roadmap.

### CODE REVIEW

**Comment by pptyasar** [comment]
Oops I also added
https://github.com/kamranahmedse/developer-roadmap/pull/1835

**Comment by dmdbilal** [comment]
> Oops I also added #1835

Can you tell me what are the topics you added contents.

**Comment by pptyasar** [comment]
You can refer that in PR #1835

**Comment by dmdbilal** [comment]
> You can refer that in PR #1835 

Ok now what should I do?

**Comment by kamranahmedse** [comment]
No worries, I have resolved the conflicts and picked up the resources from both PRs. Thanks guys!

**Pull request merged**
